# Generated by Django 3.2.6 on 2021-09-22 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penfriends_app', '0004_auto_20210922_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pen_resident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='res_messages', to='penfriends_app.resident'),
            preserve_default=False,
        ),
    ]
