# Generated by Django 2.2 on 2021-09-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penfriends_app', '0002_message_unread'),
        ('penfriends_app', '0002_auto_20210919_0049'),
    ]

    operations = [
    ]
