# Generated by Django 3.2.6 on 2021-09-22 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0005_alter_user_id'),
        ('penfriends_app', '0003_merge_20210920_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_messages', to='login_registration_app.user'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
