# Generated by Django 2.2 on 2021-10-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penfriends_app', '0010_auto_20211018_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
