# Generated by Django 2.2 on 2021-10-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penfriends_app', '0013_auto_20211018_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='picture',
            field=models.ImageField(default='default_img.png', upload_to=''),
        ),
    ]
